import type { Metadata } from "next";
import "./globals.css";
import { satoshi } from "./fonts";
import Navbar from "@/components/layout/Navbar";



export const metadata: Metadata = {
  title: "Goldexhub",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>)  {
  return (
    <html
      lang="en"
      className={`${satoshi.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
